# Generated by Django 5.2.15 on 2026-07-10 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('graduation_year', models.CharField(blank=True, max_length=10)),
                ('current_status', models.CharField(blank=True, max_length=100)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('technical_skills', models.JSONField(blank=True, default=list)),
                ('soft_skills', models.JSONField(blank=True, default=list)),
                ('dream_role', models.CharField(blank=True, max_length=100)),
                ('dream_company', models.CharField(blank=True, max_length=100)),
                ('expected_salary', models.CharField(blank=True, max_length=100)),
                ('preferred_industry', models.CharField(blank=True, max_length=100)),
                ('preferred_work_type', models.CharField(blank=True, max_length=100)),
                ('learning_style', models.JSONField(blank=True, default=list)),
                ('work_style', models.CharField(blank=True, max_length=100)),
                ('decision_making', models.CharField(blank=True, max_length=100)),
                ('team_preference', models.CharField(blank=True, max_length=100)),
                ('leadership_preference', models.CharField(blank=True, max_length=100)),
                ('career_obstacles', models.TextField(blank=True)),
                ('confidence_level', models.CharField(blank=True, max_length=50)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('resume_text', models.TextField(blank=True)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
