# Generated by Django 5.2.15 on 2026-07-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
